# -*- mode: python ; coding: utf-8 -*-

from PyInstaller.utils.hooks import collect_data_files

hidden_imports = [
    'ocrmypdf',
    'ocrmypdf._options',
    'ocrmypdf._validation',
    'ocrmypdf._validation_coordinator',
    'ocrmypdf._plugin_manager',
    'ocrmypdf._plugin_registry',
    'ocrmypdf._sync',
    'ocrmypdf._runner',
    'ocrmypdf._reader',
    'ocrmypdf._version',
    'ocrmypdf._graft',
    'ocrmypdf._jobcontext',
    'ocrmypdf._logging',
    'ocrmypdf._metadata',
    'ocrmypdf._pipeline',
    'ocrmypdf._pipelines',
    'ocrmypdf._pipelines._common',
    'ocrmypdf._pipelines.ocr',
    'ocrmypdf._pipelines.pdf_to_hocr',
    'ocrmypdf._pipelines.hocr_to_ocr_pdf',
    'ocrmypdf.api',
    'ocrmypdf.builtin_plugins',
    'ocrmypdf.builtin_plugins.concurrency',
    'ocrmypdf.builtin_plugins.default_filters',
    'ocrmypdf.builtin_plugins.ghostscript',
    'ocrmypdf.builtin_plugins.null_ocr',
    'ocrmypdf.builtin_plugins.optimize',
    'ocrmypdf.builtin_plugins.pypdfium',
    'ocrmypdf.builtin_plugins.tesseract_ocr',
    'ocrmypdf.extra_plugins',
    'ocrmypdf.extra_plugins.semfree',
    'ocrmypdf._exec',
    'ocrmypdf._exec._probe',
    'ocrmypdf._exec.ghostscript',
    'ocrmypdf._exec.jbig2enc',
    'ocrmypdf._exec.pngquant',
    'ocrmypdf._exec.tesseract',
    'ocrmypdf._exec.unpaper',
    'ocrmypdf._exec.verapdf',
    'ocrmypdf.subprocess',
    'ocrmypdf.subprocess._check',
    'ocrmypdf.subprocess._run',
    'ocrmypdf.subprocess._version',
    'ocrmypdf.subprocess._windows',
    'ocrmypdf.font',
    'ocrmypdf.font.font_manager',
    'ocrmypdf.font.font_provider',
    'ocrmypdf.font.multi_font_manager',
    'ocrmypdf.font.system_font_provider',
    'ocrmypdf.fpdf_renderer',
    'ocrmypdf.fpdf_renderer.renderer',
    'ocrmypdf.hocrtransform',
    'ocrmypdf.hocrtransform.hocr_parser',
    'ocrmypdf.imageops',
    'ocrmypdf.languages',
    'ocrmypdf.models',
    'ocrmypdf.models.ocr_element',
    'ocrmypdf.optimize',
    'ocrmypdf.pdfa',
    'ocrmypdf.pdfinfo',
    'ocrmypdf.pdfinfo.info',
    'ocrmypdf.pdfinfo.layout',
    'ocrmypdf.pdfinfo._worker',
    'ocrmypdf.pdfinfo._contentstream',
    'ocrmypdf.pdfinfo._image',
    'ocrmypdf.pdfinfo._types',
    'ocrmypdf.pluginspec',
    'ocrmypdf.quality',
    'ocrmypdf.subprocess',
    'ocrmypdf.subprocess._check',
    'ocrmypdf.subprocess._run',
    'ocrmypdf.subprocess._version',
    'ocrmypdf.subprocess._windows',
]

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('bin', 'bin')] + collect_data_files('ocrmypdf'),
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Simple-PDF-OCR',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Simple-PDF-OCR',
)
